### ISSUE TITLE
Maybe this should be modified to camera.device@3.2-impl.

### ISSUE THREAD

**Issue by GuaiYiHu** [Demon000/device_xiaomi_libra#10]
https://github.com/Demon000/device_xiaomi_libra/blob/cc83e59e4b385b4800e65889ce45142213a29835/device.mk#L101

**Comment by Demon000** [comment]
3.2 is for Camera HAL 3 which we don't have.

**Comment by GuaiYiHu** [comment]
With this I can see camera in aida64

**Comment by Demon000** [comment]
And can you use it? 😛

**Comment by GuaiYiHu** [comment]
Nop~~ XD
