### ISSUE TITLE
dpmd cannot be used

### ISSUE THREAD

**Issue by GuaiYiHu** [Demon000/device_xiaomi_libra#12]
https://github.com/Demon000/device_xiaomi_libra/blob/2eaa99dc1a035f66efbedc4da4079ec1a526a5fa/rootdir/init.qcom.rc#L377

dev="sdcardfs" ino=3491673 scontext=u:r:init:s0 tcontext=u:object_r:sdcardfs:s0 tclass=file permissive=1
09-14 16:34:15.250  3841  3841 I chatty  : uid=0(root) /system/bin/dpmd expire 2 lines
--------- beginning of crash
09-14 16:34:15.300  3843  3843 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 3843 (dpmd)
09-14 16:34:15.339  3846  3846 I crash_dump64: obtaining output fd from tombstoned
09-14 16:34:15.340   625   625 I /system/bin/tombstoned: received crash request for pid 3843
09-14 16:34:15.343  3846  3846 I crash_dump64: performing dump of process 3843 (target tid = 3843)
09-14 16:34:15.343  3846  3846 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-14 16:34:15.343  3846  3846 F DEBUG   : Build fingerprint: 'Xiaomi/lineage_leo/leo:8.0.0/OPR6.170623.012/88a430ebe4:userdebug/test-keys'
09-14 16:34:15.343  3846  3846 F DEBUG   : Revision: '0'
09-14 16:34:15.343  3846  3846 F DEBUG   : ABI: 'arm64'
09-14 16:34:15.343  3846  3846 F DEBUG   : pid: 3843, tid: 3843, name: dpmd  >>> /system/bin/dpmd <<<
09-14 16:34:15.343  3846  3846 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-14 16:34:15.343  3846  3846 F DEBUG   :     x0   0000000000000000  x1   0000000000000f03  x2   0000000000000006  x3   0000000000000008
09-14 16:34:15.344  3846  3846 F DEBUG   :     x4   6f2e6c6e62702e71  x5   6f2e6c6e62702e71  x6   6f2e6c6e62702e71  x7   7f7f7f7f7f7f7f7f
09-14 16:34:15.344  3846  3846 F DEBUG   :     x8   0000000000000083  x9   a57dbcbc140738ff  x10  0000000000000000  x11  0000000000000001
09-14 16:34:15.344  3846  3846 F DEBUG   :     x12  00000000000028af  x13  000000770af88cf4  x14  000000770af88998  x15  0000000000000000
09-14 16:34:15.344  3846  3846 F DEBUG   :     x16  000000770afa6308  x17  000000770af48214  x18  00000000000151ac  x19  0000000000000f03
09-14 16:34:15.344  3846  3846 F DEBUG   :     x20  0000000000000f03  x21  000000770a9db2fc  x22  000000770a9f9280  x23  000000770a9f9008
09-14 16:34:15.344  3846  3846 F DEBUG   :     x24  00000000ffffffff  x25  0000000000000000  x26  0000000000000000  x27  0000000000000000
09-14 16:34:15.344  3846  3846 F DEBUG   :     x28  0000000000000000  x29  0000007fcd57bbe0  x30  000000770aefb7c0
09-14 16:34:15.344  3846  3846 F DEBUG   :     sp   0000007fcd57bba0  pc   000000770af4821c  pstate 0000000060000000
09-14 16:34:15.346  3846  3846 F DEBUG   : 
09-14 16:34:15.346  3846  3846 F DEBUG   : backtrace:
09-14 16:34:15.346  3846  3846 F DEBUG   :     #00 pc 000000000006a21c  /system/lib64/libc.so (tgkill+8)
09-14 16:34:15.346  3846  3846 F DEBUG   :     #01 pc 000000000001d7bc  /system/lib64/libc.so (abort+88)
09-14 16:34:15.346  3846  3846 F DEBUG   :     #02 pc 00000000000117d8  /system/vendor/lib64/libdpmframework.so (_ZN3Dpm3runEv+520)
09-14 16:34:15.346  3846  3846 F DEBUG   :     #03 pc 00000000000045a4  /system/bin/dpmd
09-14 16:34:15.346  3846  3846 F DEBUG   :     #04 pc 000000000000237c  /system/bin/dpmd
09-14 16:34:15.346  3846  3846 F DEBUG   :     #05 pc 0000000000004690  /system/bin/dpmd
09-14 16:34:15.346  3846  3846 F DEBUG   :     #06 pc 000000000001b6a8  /system/lib64/libc.so (__libc_init+88)
09-14 16:34:15.346  3846  3846 F DEBUG   :     #07 pc 0000000000002240  /system/bin/dpmd
09-14 16:34:15.374  1003  2335 W NativeCrashListener: Couldn't find ProcessRecord for pid 3843
09-14 16:34:15.375   625   625 E /system/bin/tombstoned: Tombstone written to: /data/tombstones//tombstone_02

**Comment by Demon000** [comment]
Fix it.
