### ISSUE TITLE
Los15.1

### ISSUE THREAD

**Issue by lrinQVQ** [Demon000/device_xiaomi_libra#17]
hi~
I try to building Los15.1 for libra.

This is my repopick:https://gist.github.com/lrinQVQ/387d70b248d72f9069b2abefb08444ce
and
Power Cherry Pick:https://gist.github.com/lrinQVQ/d95ad52ca3871c0bbf5ed37b05af4300
https://gist.github.com/lrinQVQ/8e876c25771f946e38f05a1dd19e868f
https://gist.github.com/lrinQVQ/4e9c951dbe5a3ed91ab9666132f13e3f

but this building can't boot 
Kernel is work well,this is log:https://gist.github.com/lrinQVQ/f3e7db72ae5a3a932d8efaa7d6441d21
I found some problems in system boot logcat:https://gist.github.com/lrinQVQ/84e77788cc26cf7a9fb7c75f72ac3deb
I think the problem may be starting system services.
and
this is full logcat:https://gist.github.com/lrinQVQ/670853fdca5d7c69696b20e7747706e1

Can i participate in the development of libra?0.0
Thanks~

**Comment by Demon000** [comment]
I know that it doesn't boot.

cnd service needs to be sed-ed to remove android.hidl.base@1.0.so

rild looks like crashing too, for some reason it's using our old protobuf hacked lib

**Comment by lrinQVQ** [comment]
Thanks~
I will try to fix these problems,if i can ~~>_<~~

**Comment by lrinQVQ** [comment]
And https://gist.github.com/lrinQVQ/84e77788cc26cf7a9fb7c75f72ac3deb
Seems to be caused by the framework?
this caused my phone to restart indefinitely

**Comment by Demon000** [comment]
I don't have that error.

**Comment by lrinQVQ** [comment]
thanks for your help~

**Comment by Demon000** [comment]
I solved everything
Though I don't know if RIL works since my SIM is too small and I don't have an adaptor.

**Comment by lrinQVQ** [comment]
wow~
I'll try to test RIL work.

**Comment by lrinQVQ** [comment]
Building about two hours.
Maybe I encountered a little problem,I still can not boot

**Comment by Demon000** [comment]
Did you pick the kernel commits?

**Comment by lrinQVQ** [comment]
Yes~
I pick vendor device kernel latest commit.
I rebuild with userdebug,I 'll try again
This should be my problem XD

**Comment by lrinQVQ** [comment]
Then i dowload your building form https://androidfilehost.com/?fid=962021903579500649
SIM work well~
Camera work well~
Bluetooth work well~
WLAN work well~
Thanks for your work~
