### ISSUE TITLE
fix china telecom

### ISSUE THREAD

**Issue by lrinQVQ** [Demon000/device_xiaomi_libra#6]
hi~
to many user tell me in android_7.1.2, china telecom can't make a telephone call
if telephony default network is TD-SCDMA, GSM/WCDMA and LTE mode china telecom user can't make a telephone call
![2017-05-24 18-23-23](https://cloud.githubusercontent.com/assets/12861134/26399062/2435caf4-40ae-11e7-8516-915b70e9b753.png)
set ro.telephony.default_network to global mode
"ro.telephony.default_network=10"
can fix it
http://www.miui.com/thread-7949579-1-1.html

**Comment by Demon000** [comment]
Wouldn't this change the behaviour for people outside of China too?

**Comment by lrinQVQ** [comment]
I only test china telecom,but this can fix all of TD-LTE and FDD-LTE hybrid networking.

**Comment by GuaiYiHu** [comment]
I let those guys set this by themselves... No need to add this in fact...
